
analyzer:
  exclude: [build/**, "**/*.freezed.dart", "**/*.g.dart", "**/*.gr.dart", "**/*.gen.dart", "**/*.swagger.dart", "**/*.chopper.dart"]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Built-in rules
    body_might_complete_normally_nullable: ignore

    # Error rules
    # avoid_dynamic_calls: error
    avoid_empty_else: warning
    avoid_returning_null_for_future: warning
    avoid_slow_async_io: error
    avoid_type_to_string: warning
    cancel_subscriptions: error
    close_sinks: warning
    empty_statements: warning
    hash_and_equals: warning
    iterable_contains_unrelated_type: warning
    list_remove_unrelated_type: warning
    use_build_context_synchronously: error

    # Style Rules
    always_declare_return_types: error
    always_put_control_body_on_new_line: warning
    avoid_equals_and_hash_code_on_mutable_classes: error
    avoid_field_initializers_in_const_classes: warning
    avoid_function_literals_in_foreach_calls: warning
    avoid_returning_this: warning
    avoid_unused_constructor_parameters: warning
    unused_field: info
    avoid_void_async: error
    await_only_futures: warning
    cast_nullable_to_non_nullable: warning
    conditional_uri_does_not_exist: warning
    curly_braces_in_flow_control_structures: warning
    no_leading_underscores_for_local_identifiers: warning
    null_closures: error
    only_throw_errors: warning
    parameter_assignments: error
    prefer_asserts_with_message: warning
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_final_fields: error
    prefer_final_in_for_each: error
    prefer_final_locals: error
    prefer_function_declarations_over_variables: warning
    prefer_generic_function_type_aliases: warning
    prefer_initializing_formals: warning
    prefer_typing_uninitialized_variables: error
    provide_deprecation_message: warning
    recursive_getters: warning
    tighten_type_of_initializing_formals: warning
    type_annotate_public_apis: error
    unawaited_futures: warning
    unnecessary_await_in_return: warning
    unnecessary_this: warning
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: warning
    use_string_buffers: warning
    use_enums: warning
    invalid_annotation_target: ignore

    # Pub Rules
    depend_on_referenced_packages: error
    secure_pubspec_urls: warning
    library_private_types_in_public_api: ignore
    unused_element: ignore

linter:
  rules:
    # Error rules
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_print
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - collection_methods_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - unsafe_html
    - use_build_context_synchronously # experimental
    - use_key_in_widget_constructors
    - valid_regexps

    # Style Rules
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - conditional_uri_does_not_exist
    - constant_identifier_names
    - combinators_ordering
    - curly_braces_in_flow_control_structures
    - deprecated_consistency
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - implementation_imports
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    - missing_whitespace_between_adjacent_strings
    - no_default_cases # experimental
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - non_constant_identifier_names
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - null_closures
    - omit_local_variable_types
    - only_throw_errors
    - overridden_fields
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - require_trailing_commas # experimental
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks # experimental
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations # experimental
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unreachable_from_main # experimental
    - use_colored_box
    - use_decorated_box
    - use_enums # experimental
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_rethrow_when_possible
    - use_string_buffers
    - use_string_in_part_of_directives
    - use_super_parameters # experimental
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    - void_checks
    - implicit_reopen 
    - invalid_case_patterns
    - no_self_assignments
    - avoid_final_parameters
    - avoid_private_typedef_functions
    # - flutter_style_todos
    - no_runtimeType_toString
    - no_literal_bool_comparisons
    - package_prefixed_library_names
    - prefer_expression_function_bodies
    - use_late_for_private_fields_and_variables

    # Pub Rules
    - depend_on_referenced_packages
    - package_names
    - secure_pubspec_urls

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-methods: 12
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - avoid-collection-methods-with-unrelated-types
    - avoid-dynamic:
        severity: error
    - avoid-global-state:
        severity: error
    - avoid-missing-enum-constant-in-map:
        severity: error
    - avoid-nested-conditional-expressions
    - avoid-non-null-assertion
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions:
        severity: style
    - avoid-unnecessary-type-casts:
        severity: style
    - avoid-unrelated-type-assertions:
        severity: style
    - binary-expression-operand-order
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block- no-equal-arguments
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-correct-identifier-length:
        exceptions: ['id', 'to', 'of']
        max-identifier-length: 30
        min-identifier-length: 3
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    - always-remove-listener # experimental
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - prefer-intl-name
    - provide-correct-intl-args
    - prefer-moving-to-variable
    - prefer-commenting-analyzer-ignores
    - avoid-non-ascii-symbols
    - format-comment
    - avoid-expanded-as-spacer
    - avoid-duplicate-exports
    - avoid-shrink-wrap-in-lists
    - avoid-top-level-members-in-tests
    - prefer-correct-edge-insets-constructor
    - prefer-enums-by-name
    - avoid-passing-async-when-sync-expected
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - avoid-redundant-async
    - prefer-correct-test-file-name
    - prefer-iterable-of
    - missing-test-assertion
    - avoid-cascade-after-if-null
    - avoid-double-slash-imports
    - prefer-using-list-view
    - avoid-unnecessary-conditionals
    - use-setstate-synchronously
  rules-exclude:
    - test/**
  anti-patterns:
    - long-method
    - long-parameter-list