name: shop
description: Shop

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.2'
  flutter: '>=2.10.5'

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_sliders: ^20.3.61
  flutter_vibrate: ^1.3.0
  
  # SDK extensions
  async: ^2.8.2
  collection: ^1.15.0
  meta: ^1.7.0

  # System
  path_provider: ^2.0.0
  path: ^1.8.0
  platform_info: ^3.1.0

  # Data manipulation
  pure: ^0.2.0
  fast_immutable_collections: ^7.0.0
  stream_transform: ^2.0.0

  # BLoC
  stream_bloc: ^0.5.1

  # Flutter integrations
  flutter_bloc: ^8.0.1
  provider: ^6.0.2

  # Code generation
  freezed_annotation: ^2.1.0
  json_annotation: ^4.4.0
  select_annotation: ^0.2.0

  # Internationalization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter 

  # Logging
  l: ^3.1.0
  sentry_flutter: ^6.2.2
  stack_trace: ^1.10.0

  # Persistance
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.13

  # HTTP
  dio: ^4.0.4
  retrofit: ^3.0.1

  # Navigation
  auto_route: ^5.0.1

dev_dependencies:
  # Analyzer extensions
  dart_code_metrics: ^4.13.0
  purple_metrics_lints: ^0.3.0

  # Utils
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.0.5

  # Code generation
  build_runner: ^2.1.7
  auto_route_generator: ^5.0.2
  select: ^0.3.1
  retrofit_generator: ^4.0.1
  hive_generator:
    git:
      url: https://github.com/yura2000/hive.git
      ref: master
      path: hive_generator/
  freezed: ^2.1.0+1
  json_serializable: ^6.1.4
  flutter_gen_runner: ^4.1.5

  # Tooling
  grinder: ^0.9.1
  coverage: ^1.0.3
  test: ^1.21.1


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "asset/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "asset/logo.png"

flutter_gen:
  output: lib/src/core/resources
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - asset/
    - asset/image/
  fonts:
    - family: Inter
      fonts:
          - asset: asset/font/inter/Inter-ExtraLight.ttf
            weight: 200
          - asset: asset/font/inter/Inter-Light.ttf
            weight: 300
          - asset: asset/font/inter/Inter-Regular.ttf
            weight: 400
          - asset: asset/font/inter/Inter-Medium.ttf
            weight: 500
          - asset: asset/font/inter/Inter-SemiBold.ttf
            weight: 600
          - asset: asset/font/inter/Inter-Bold.ttf
            weight: 700
          - asset: asset/font/inter/Inter-ExtraBold.ttf
            weight: 800

