// Mocks generated by Mockito 5.3.2 from annotations
// in shop/src/feature/shop/model/product_characteristics/product_characteristics.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:shop/src/feature/shop/model/product_characteristics/product_characteristics.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake$ProductCharacteristicCopyWith_0<$Res> extends _i1.SmartFake
    implements _i2.$ProductCharacteristicCopyWith<$Res> {
  _Fake$ProductCharacteristicCopyWith_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductCharacteristic].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductCharacteristic extends _i1.Mock implements _i2.ProductCharacteristic {
  @override
  int get weight => (super.noSuchMethod(
        Invocation.getter(#weight),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  int get price => (super.noSuchMethod(
        Invocation.getter(#price),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  String get manufactureCountry => (super.noSuchMethod(
        Invocation.getter(#manufactureCountry),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  int get expirationDateInDays => (super.noSuchMethod(
        Invocation.getter(#expirationDateInDays),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  _i2.$ProductCharacteristicCopyWith<_i2.ProductCharacteristic> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$ProductCharacteristicCopyWith_0<_i2.ProductCharacteristic>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$ProductCharacteristicCopyWith_0<_i2.ProductCharacteristic>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$ProductCharacteristicCopyWith<_i2.ProductCharacteristic>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
