// Mocks generated by Mockito 5.3.2 from annotations
// in shop/src/feature/shop/model/shop/shop.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:shop/src/feature/shop/model/product/product.dart' as _i3;
import 'package:shop/src/feature/shop/model/shop/shop.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake$ShopCopyWith_0<$Res> extends _i1.SmartFake
    implements _i2.$ShopCopyWith<$Res> {
  _Fake$ShopCopyWith_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Shop].
///
/// See the documentation for Mockito's code generation for more information.
class MockShop extends _i1.Mock implements _i2.Shop {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  int get deliveryTimeInMinutes => (super.noSuchMethod(
        Invocation.getter(#deliveryTimeInMinutes),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  int get deliveryPrice => (super.noSuchMethod(
        Invocation.getter(#deliveryPrice),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  String get photoUrl => (super.noSuchMethod(
        Invocation.getter(#photoUrl),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  List<_i3.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i3.Product>[],
        returnValueForMissingStub: <_i3.Product>[],
      ) as List<_i3.Product>);
  @override
  _i2.$ShopCopyWith<_i2.Shop> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$ShopCopyWith_0<_i2.Shop>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$ShopCopyWith_0<_i2.Shop>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$ShopCopyWith<_i2.Shop>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
