// Mocks generated by Mockito 5.3.2 from annotations
// in shop/src/feature/shop/model/product/product.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:shop/src/feature/shop/model/product/product.dart' as _i3;
import 'package:shop/src/feature/shop/model/product_characteristics/product_characteristics.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductCharacteristic_0 extends _i1.SmartFake
    implements _i2.ProductCharacteristic {
  _FakeProductCharacteristic_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProductCopyWith_1<$Res> extends _i1.SmartFake
    implements _i3.$ProductCopyWith<$Res> {
  _Fake$ProductCopyWith_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Product].
///
/// See the documentation for Mockito's code generation for more information.
class MockProduct extends _i1.Mock implements _i3.Product {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get photoUrl => (super.noSuchMethod(
        Invocation.getter(#photoUrl),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i2.ProductCharacteristic get characteristic => (super.noSuchMethod(
        Invocation.getter(#characteristic),
        returnValue: _FakeProductCharacteristic_0(
          this,
          Invocation.getter(#characteristic),
        ),
        returnValueForMissingStub: _FakeProductCharacteristic_0(
          this,
          Invocation.getter(#characteristic),
        ),
      ) as _i2.ProductCharacteristic);
  @override
  _i3.$ProductCopyWith<_i3.Product> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$ProductCopyWith_1<_i3.Product>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$ProductCopyWith_1<_i3.Product>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i3.$ProductCopyWith<_i3.Product>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
